<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.52">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4&nbsp; Categorical Data Analysis – Statistical Computing and Programming</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./05-robust_statistics.html" rel="next">
<link href="./03-summarising_data.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04-categorical_data_analysis.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Categorical Data Analysis</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistical Computing and Programming</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro_to_R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-intro_to_python.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction to Python</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-summarising_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Summarising Numerical Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-categorical_data_analysis.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Categorical Data Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-robust_statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Robust Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-intro_to_sas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Introduction to SAS</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-2_sample_tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">2-sample Hypothesis Tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Simulation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Academic References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contents</h2>
   
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">4.1</span> Introduction</a></li>
  <li><a href="#contingency-tables" id="toc-contingency-tables" class="nav-link" data-scroll-target="#contingency-tables"><span class="header-section-number">4.2</span> Contingency Tables</a></li>
  <li><a href="#tests-for-independence" id="toc-tests-for-independence" class="nav-link" data-scroll-target="#tests-for-independence"><span class="header-section-number">4.3</span> Tests for Independence</a></li>
  <li><a href="#measures-of-association" id="toc-measures-of-association" class="nav-link" data-scroll-target="#measures-of-association"><span class="header-section-number">4.4</span> Measures of Association</a></li>
  <li><a href="#visualisations" id="toc-visualisations" class="nav-link" data-scroll-target="#visualisations"><span class="header-section-number">4.5</span> Visualisations</a></li>
  <li><a href="#further-readings" id="toc-further-readings" class="nav-link" data-scroll-target="#further-readings"><span class="header-section-number">4.6</span> Further readings</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">4.7</span> References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Categorical Data Analysis</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">4.1</span> Introduction</h2>
<p>A variable is known as a <em>categorical variable</em> if each observation belongs to one of a set of categories. Examples of categorical variables are: gender, religion, race and type of residence.</p>
<p>Categorical variables are typically modeled using discrete random variables, which are strictly defined in terms whether or not the support is countable. The alternative to categorical variables are quantitative variables, which are typically modeled using continuous random variables.</p>
<p>Another method for distinguishing between quantitative and categorical variables is to ask if there is a meaningful distance between any two points in the data. If such a distance is meaningful then we have quantitative data. For instance, it makes sense to compute the difference in systolic blood pressure between subjects but it does not make sense to consider the mathematical operation (“smoker” - “non-smoker”).</p>
<p>It is important to identify which type of data we have (quantitative or categorical), since it affects the exploration techniques that we can apply.</p>
<p>There are two sub-types of categorical variables:</p>
<ul>
<li>A categorical variable is <em>ordinal</em> if the observations can be ordered, but do not have specific quantitative values.</li>
<li>A categorical variable is <em>nominal</em> if the observations can be classified into categories, but the categories have no specific ordering.</li>
</ul>
<p>In this topic, we shall discuss techniques for identifying the presence, and for measuring the strength, of the association between two categorical variables.</p>
</section>
<section id="contingency-tables" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="contingency-tables"><span class="header-section-number">4.2</span> Contingency Tables</h2>
<div id="exm-chest-pain" class="theorem example" style="background-color: #D5D1D1; padding: 20px">
<p><span class="theorem-title"><strong>Example 4.1 (Chest Pain and Gender)</strong></span> </p>
<p>Suppose that 1073 NUH patients who were at high risk for cardiovascular disease (CVD) were randomly sampled. They were then queried on two things:</p>
<ol type="1">
<li>Had they experienced the onset of severe chest pain in the preceding 6 months? (yes/no)</li>
<li>What was their gender? (male/female)</li>
</ol>
<p>The data would probably have been recorded in the following format (only first few rows shown):</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Gender</th>
<th style="text-align: left;">Pain</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">female</td>
<td style="text-align: left;">no pain</td>
</tr>
<tr class="even">
<td style="text-align: left;">male</td>
<td style="text-align: left;">no pain</td>
</tr>
<tr class="odd">
<td style="text-align: left;">female</td>
<td style="text-align: left;">no pain</td>
</tr>
<tr class="even">
<td style="text-align: left;">male</td>
<td style="text-align: left;">no pain</td>
</tr>
<tr class="odd">
<td style="text-align: left;">female</td>
<td style="text-align: left;">no pain</td>
</tr>
<tr class="even">
<td style="text-align: left;">male</td>
<td style="text-align: left;">pain</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>However, it would probably be summarised and presented in this format, which is known as a <em>contingency table</em>.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">pain</th>
<th style="text-align: right;">no pain</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">male</td>
<td style="text-align: right;">46</td>
<td style="text-align: right;">474</td>
</tr>
<tr class="even">
<td style="text-align: left;">female</td>
<td style="text-align: right;">37</td>
<td style="text-align: right;">516</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>In a contingency table, each observation from the dataset falls in exactly one of the cells. The sum of all entries in the cells equals the number of independent observations in the dataset.</p>
</div>
<p>All the techniques we shall touch upon in this chapter are applicable to contingency tables.</p>
</section>
<section id="tests-for-independence" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="tests-for-independence"><span class="header-section-number">4.3</span> Tests for Independence</h2>
<p>In the contingency table above, the two categorical variables are <em>Gender</em> and <em>Presence/absence of Pain</em>. With contingency tables, the main inferential task usually relates to assessing the association between the two categorical variables.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Independent Categorical Variables">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Independent Categorical Variables
</div>
</div>
<div class="callout-body-container callout-body">
<p>If two categorical variables are <strong>independent</strong>, then the joint distribution of the variables would be equal to the product of the marginals. If two variables are not independent, we say that they are <strong>associated</strong>.</p>
</div>
</div>
<section id="chi2-test-for-independence" class="level3">
<h3 class="anchored" data-anchor-id="chi2-test-for-independence"><span class="math inline">\(\chi^2\)</span>-Test for Independence</h3>
<p>The <span class="math inline">\(\chi^2\)</span>-test uses the definition above to assess if two variables in a contingency table are associated. The null and alternative hypotheses are</p>
<p><span class="math display">\[\begin{eqnarray*}
H_0 &amp;:&amp; \text{The two variables are indepdendent.}  \\
H_1 &amp;:&amp; \text{The two variables are not indepdendent.}
\end{eqnarray*}\]</span></p>
<p>Under the null hypothesis, we can estimate the joint distribution from the observed marginal counts. Based on this estimated joint distribution, we then compute <em>expected</em> counts (which may not be integers) for each cell. The test statistic essentially compares the deviation of <em>observed</em> cell counts from the expected cell counts.</p>
<div id="exm-chest-pain-2" class="theorem example" style="background-color: #D5D1D1; padding: 20px">
<p><span class="theorem-title"><strong>Example 4.2 (Chest Pain and Gender Expected Counts)</strong></span> </p>
<p>Continuing from <a href="#exm-chest-pain" class="quarto-xref">Example&nbsp;<span>4.1</span></a>, we can compute the estimated marginals using row and column proportions</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>────────────────────────────────────────────────────────────────────────────── 
chest_tab (table)

Summary: 
n: 1'073, rows: 2, columns: 2

Pearson's Chi-squared test (cont. adj):
  X-squared = 1.4555, df = 1, p-value = 0.2276
Fisher's exact test p-value = 0.2089

                                     
                 pain   no pain   Sum
                                     
male     freq      46       474   520
         p.row   8.8%     91.2%     .
         p.col  55.4%     47.9% 48.5%
                                     
female   freq      37       516   553
         p.row   6.7%     93.3%     .
         p.col  44.6%     52.1% 51.5%
                                     
Sum      freq      83       990 1'073
         p.row   7.7%     92.3%     .
         p.col      .         .     .
                                     

────────────────────
' 95% conf. level</code></pre>
</div>
</div>
<p>In the output above, ignore the p-values for now.. We’ll get to those in a minute. Let <span class="math inline">\(X\)</span> represent gender and <span class="math inline">\(Y\)</span> represent chest pain. Then from the estimated proportions in the “Sum” row and colums, we can read off the following estimated probabilities</p>
<p><span class="math display">\[\begin{eqnarray*}
\widehat{P}(X = \text{male}) &amp;=&amp; 0.485  \\
\widehat{P}(Y = \text{pain}) &amp;=&amp; 0.077
\end{eqnarray*}\]</span></p>
<p>Consequently, <em>under <span class="math inline">\(H_0\)</span></em>, we would estimate <span class="math display">\[
\widehat{P}(X = \text{male},\, Y= \text{pain}) = 0.485 \times 0.077 \approx 0.04
\]</span></p>
<p>From a sample of size 1073, the expected count for this cell is then</p>
<p><span class="math display">\[
0.04 \times 1073 = 42.92
\]</span></p>
</div>
<p>Using the approach above, we can derive a general formula for the expected count in each cell: <span class="math display">\[
\text{Expected count} = \frac{\text{Row total} \times \text{Column total}}{\text{Total sample size}}
\]</span></p>
<p>The formula for the <span class="math inline">\(\chi^2\)</span>-test statistic (with continuity correction) is: <span id="eq-chi-sq"><span class="math display">\[
\chi^2 = \sum \frac{(|\text{expected} - \text{observed} | - 0.50 )^2}{\text{expected count}}
\tag{4.1}\]</span></span></p>
<p>The sum is taken over every cell in the table. Hence in a <span class="math inline">\(2\times2\)</span>, as in <a href="#exm-chest-pain" class="quarto-xref">Example&nbsp;<span>4.1</span></a>, there would be 4 terms in the summation.</p>
<div id="exm-chest-pain-3" class="theorem example" style="background-color: #D5D1D1; padding: 20px">
<p><span class="theorem-title"><strong>Example 4.3 (Chest Pain and Gender <span class="math inline">\(\chi^2\)</span> Test)</strong></span> </p>
<p>Let us see how we can apply and interpret the <span class="math inline">\(\chi^2\)</span>-test for the data in <a href="#exm-chest-pain" class="quarto-xref">Example&nbsp;<span>4.1</span></a>.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true">R code</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Python code</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a>x <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">46</span>, <span class="dv">37</span>, <span class="dv">474</span>, <span class="dv">516</span>), <span class="at">nrow=</span><span class="dv">2</span>)</span>
<span id="cb2-2"><a href="#cb2-2"></a><span class="fu">dimnames</span>(x) <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="fu">c</span>(<span class="st">"male"</span>, <span class="st">"female"</span>), <span class="fu">c</span>(<span class="st">"pain"</span>, <span class="st">"no pain"</span>))</span>
<span id="cb2-3"><a href="#cb2-3"></a>chest_tab <span class="ot">&lt;-</span> <span class="fu">as.table</span>(x)</span>
<span id="cb2-4"><a href="#cb2-4"></a></span>
<span id="cb2-5"><a href="#cb2-5"></a>chisq_output <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(chest_tab)</span>
<span id="cb2-6"><a href="#cb2-6"></a>chisq_output</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  chest_tab
X-squared = 1.4555, df = 1, p-value = 0.2276</code></pre>
</div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb4-2"><a href="#cb4-2"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb4-3"><a href="#cb4-3"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb4-4"><a href="#cb4-4"></a></span>
<span id="cb4-5"><a href="#cb4-5"></a>chest_array <span class="op">=</span> np.array([[<span class="dv">46</span>, <span class="dv">474</span>], [<span class="dv">37</span>, <span class="dv">516</span>]])</span>
<span id="cb4-6"><a href="#cb4-6"></a></span>
<span id="cb4-7"><a href="#cb4-7"></a>chisq_output <span class="op">=</span> stats.chi2_contingency(chest_array)</span>
<span id="cb4-8"><a href="#cb4-8"></a></span>
<span id="cb4-9"><a href="#cb4-9"></a><span class="bu">print</span>(<span class="ss">f"The p-value is </span><span class="sc">{</span>chisq_output<span class="sc">.</span>pvalue<span class="sc">:.3f}</span><span class="ss">."</span>)</span>
<span id="cb4-10"><a href="#cb4-10"></a><span class="co">## The p-value is 0.228.</span></span>
<span id="cb4-11"><a href="#cb4-11"></a><span class="bu">print</span>(<span class="ss">f"The test-statistic value is </span><span class="sc">{</span>chisq_output<span class="sc">.</span>statistic<span class="sc">:.3f}</span><span class="ss">."</span>)</span>
<span id="cb4-12"><a href="#cb4-12"></a><span class="co">## The test-statistic value is 1.456.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<p>Since the <span class="math inline">\(p\)</span>-value is 0.2276, we would not reject the null hypothesis at significance level 5%. We do not have sufficient evidence to conclude that the variables are not independent.</p>
<p>To extract the expected cell counts, we can use the following code:</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true">R code</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false">Python code</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a>chisq_output<span class="sc">$</span>expected</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           pain  no pain
male   40.22367 479.7763
female 42.77633 510.2237</code></pre>
</div>
</div>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1"></a>chisq_output.expected_freq</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>array([[ 40.22367195, 479.77632805],
       [ 42.77632805, 510.22367195]])</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>The test statistic compares the above table to the <em>observed</em> table, earlier in <a href="#exm-chest-pain" class="quarto-xref">Example&nbsp;<span>4.1</span></a>.</p>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>It is only suitable to use the <span class="math inline">\(\chi^2\)</span>-test when all <em>expected cell counts</em> are larger than 5.</p>
</div>
</div>
</section>
<section id="fishers-exact-test" class="level3">
<h3 class="anchored" data-anchor-id="fishers-exact-test">Fisher’s Exact Test</h3>
<p>When the condition above is not met, we turn to Fisher’s Exact Test. The null and alternative hypothesis are the same, but the test statistic is not derived in the same way.</p>
<p>If the marginal totals are fixed, and the two variables are independent, it can be shown that the individual cell counts arise from a variant of the hypergeometric distribution. The test statistic is based on this observation. The <span class="math inline">\(p\)</span>-value is typically obtained by simulating tables with the same marginals as the observed dataset.</p>
<p>Using Fisher’s test sidesteps the need for a large sample size (which aids in the approximation of the distribution of the earlier test statistic). Hence the “Exact” in the name of the test.</p>
<div id="exm-claritin-1" class="theorem example" style="background-color: #D5D1D1; padding: 20px">
<p><span class="theorem-title"><strong>Example 4.4 (Claritin and Nervousness)</strong></span> </p>
<p>Claritin is a drug for treating allergies. However, it has a side effect of inducing nervousness in patients. From a sample of 450 subjects, 188 of them were randomly assigned to take Claritin, and the remaining were assigned to take the placebo. The observed data was as follows:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">nervous</th>
<th style="text-align: right;">not nervous</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">claritin</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">184</td>
</tr>
<tr class="even">
<td style="text-align: left;">placebo</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">260</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Here is the code to perform the Fisher Exact Test.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true">R code</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false">Python code</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a>y <span class="ot">&lt;-</span>  <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">184</span>, <span class="dv">260</span>), <span class="at">nrow=</span><span class="dv">2</span>)</span>
<span id="cb9-2"><a href="#cb9-2"></a><span class="fu">dimnames</span>(y) <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="fu">c</span>(<span class="st">"claritin"</span>, <span class="st">"placebo"</span>), <span class="fu">c</span>(<span class="st">"nervous"</span>, <span class="st">"not nervous"</span>))</span>
<span id="cb9-3"><a href="#cb9-3"></a>claritin_tab <span class="ot">&lt;-</span> <span class="fu">as.table</span>(y)</span>
<span id="cb9-4"><a href="#cb9-4"></a></span>
<span id="cb9-5"><a href="#cb9-5"></a><span class="fu">fisher.test</span>(claritin_tab)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fisher's Exact Test for Count Data

data:  claritin_tab
p-value = 0.2412
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
  0.399349 31.473382
sample estimates:
odds ratio 
  2.819568 </code></pre>
</div>
</div>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1"></a>claritin_tab <span class="op">=</span> np.array([[<span class="dv">4</span>, <span class="dv">184</span>], [<span class="dv">2</span>, <span class="dv">260</span>]])</span>
<span id="cb11-2"><a href="#cb11-2"></a></span>
<span id="cb11-3"><a href="#cb11-3"></a>stats.fisher_exact(claritin_tab)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>SignificanceResult(statistic=np.float64(2.8260869565217392), pvalue=np.float64(0.24118420183193057))</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>As the <span class="math inline">\(p\)</span>-value is 0.2412, we again do not have sufficient evidence to reject the null hypothesis and conclude that there is a significant association.</p>
<p>By the way, we can check (in R) to see that the <span class="math inline">\(\chi^2\)</span>-test would not have been appropriate:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a><span class="fu">chisq.test</span>(claritin_tab)<span class="sc">$</span>expected</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in chisq.test(claritin_tab): Chi-squared approximation may be incorrect</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>          nervous not nervous
claritin 2.506667    185.4933
placebo  3.493333    258.5067</code></pre>
</div>
</div>
</div>
</section>
<section id="chi2-test-for-r-times-c-tables" class="level3">
<h3 class="anchored" data-anchor-id="chi2-test-for-r-times-c-tables"><span class="math inline">\(\chi^2\)</span>-Test for <span class="math inline">\(r \times c\)</span> Tables</h3>
<p>So far, we have considered the situation of two categorical variables where each one has only two outcomes (2x2 table). However, it is common that we want to check the association between two nominal variables where one of them or both have more than 2 outcomes. Consider data given in the table below where both variables are nominal.</p>
<div id="exm-pol-assoc-1" class="theorem example" style="background-color: #D5D1D1; padding: 20px">
<p><span class="theorem-title"><strong>Example 4.5 (Political Association and Gender)</strong></span> </p>
<p>Consider data given in the table below where both variables are nominal. It cross-classifies poll respondents according to their gender and their political party affiliation.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Dem</th>
<th style="text-align: right;">Ind</th>
<th style="text-align: right;">Rep</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">female</td>
<td style="text-align: right;">762</td>
<td style="text-align: right;">327</td>
<td style="text-align: right;">468</td>
</tr>
<tr class="even">
<td style="text-align: left;">male</td>
<td style="text-align: right;">484</td>
<td style="text-align: right;">239</td>
<td style="text-align: right;">477</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The R code for applying the test is identical to before</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a>x <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">762</span>,<span class="dv">327</span>,<span class="dv">468</span>,<span class="dv">484</span>,<span class="dv">239</span>,<span class="dv">477</span>), <span class="at">ncol=</span><span class="dv">3</span>, <span class="at">byrow=</span><span class="cn">TRUE</span>)</span>
<span id="cb16-2"><a href="#cb16-2"></a><span class="fu">dimnames</span>(x) <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="fu">c</span>(<span class="st">"female"</span>, <span class="st">"male"</span>), </span>
<span id="cb16-3"><a href="#cb16-3"></a>                    <span class="fu">c</span>(<span class="st">"Dem"</span>, <span class="st">"Ind"</span>, <span class="st">"Rep"</span>))</span>
<span id="cb16-4"><a href="#cb16-4"></a>political_tab <span class="ot">&lt;-</span> <span class="fu">as.table</span>(x)</span>
<span id="cb16-5"><a href="#cb16-5"></a><span class="fu">chisq.test</span>(political_tab)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  political_tab
X-squared = 30.07, df = 2, p-value = 2.954e-07</code></pre>
</div>
</div>
<p>In this case, there is strong evidence to reject <span class="math inline">\(H_0\)</span>. At 5% level, we would reject the null hypothesis and conclude there is an association between gender and political affiliation.</p>
</div>
<p>The <span class="math inline">\(\chi^2\)</span>-test can be extended to tables larger than 2x2. In general, we might have <span class="math inline">\(r\)</span> rows and <span class="math inline">\(c\)</span> columns. The null and alternative hypotheses are identical to the 2x2 case, and the test statistic is computed in the same way. However, under the null hypothesis, the test statistic follows a <span class="math inline">\(\chi^2\)</span> distribution with <span class="math inline">\((r-1)(c-1)\)</span> degrees of freedom.</p>
<p>The <span class="math inline">\(\chi^2\)</span>-test is based on a model of independence - the expected counts are derived under this assumption. As such, it is possible to derive residuals and study them, to see where the data deviates from this model.</p>
<p>We define the <em>standardised residuals</em> to be</p>
<p><span class="math display">\[
r_{ij} = \frac{n_{ij} - \mu_{ij}}{\sqrt{\mu_{ij} (1 - p_{i+})(1 -p_{+j} )}}
\]</span> where</p>
<ul>
<li><span class="math inline">\(n_{ij}\)</span> is the observed cell count in row <span class="math inline">\(i\)</span> and column <span class="math inline">\(j\)</span> (cell <span class="math inline">\(ij\)</span>).</li>
<li><span class="math inline">\(\mu_{ij}\)</span> is the <em>expected</em> cell count in row <span class="math inline">\(i\)</span> and column <span class="math inline">\(j\)</span></li>
<li><span class="math inline">\(p_{i+}\)</span> is the marginal probability of row <span class="math inline">\(i\)</span></li>
<li><span class="math inline">\(p_{+j}\)</span> is the marginal probability of column <span class="math inline">\(j\)</span>.</li>
</ul>
<p>The residuals can be obtained from the test output. Under <span class="math inline">\(H_0\)</span>, the residuals should be close to a standard Normal distribution. If the residual for a particular cell is very large (or small), we suspect that lack of fit (to the independence model) comes from that cell.</p>
<p>For the political association table, the standardised residuals (from R) are:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a><span class="fu">chisq.test</span>(political_tab)<span class="sc">$</span>stdres</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Dem        Ind        Rep
female  4.5020535  0.6994517 -5.3159455
male   -4.5020535 -0.6994517  5.3159455</code></pre>
</div>
</div>
</section>
</section>
<section id="measures-of-association" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="measures-of-association"><span class="header-section-number">4.4</span> Measures of Association</h2>
<p>This sections covers bivariate measures of association for contingency tables.</p>
<section id="odds-ratio" class="level3">
<h3 class="anchored" data-anchor-id="odds-ratio">Odds Ratio</h3>
<p>The most generally applicable measure of association, for 2x2 tables with nominal variables, is the Odds Ratio (OR). Suppose we have <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> to be Bernoulli random variables with (population) success probabilities <span class="math inline">\(p_1\)</span> and <span class="math inline">\(p_2\)</span>.</p>
<p>We define the odds of success for <span class="math inline">\(X\)</span> to be <span class="math display">\[
\frac{p_1}{1-p_1}
\]</span> Similarly, the odds of success for random variable <span class="math inline">\(Y\)</span> is <span class="math inline">\(\frac{p_2}{1-p_2}\)</span>.</p>
<p>In order to measure the strength of their association, we use the <em>odds ratio</em>: <span class="math display">\[
\frac{p_1/ (1-p_1)}{p_2/(1-p_2)}
\]</span></p>
<p>The odds ratio can take on any value from 0 to <span class="math inline">\(\infty\)</span>.</p>
<ul>
<li>A value of 1 indicates no association between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. If <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> were independent, this is what we would observe.</li>
<li>Deviations from 1 indicate stronger association between the variables.</li>
<li>Note that deviations from 1 are not symmetric. For a given pair of variables, an association of 0.25 or 4 is the same - it is just a matter of which variable we put in the numerator odds.</li>
</ul>
<p>Due to the above asymmetry, we often use the log-odds-ratio instead: <span class="math display">\[
\log \frac{p_1/ (1-p_1)}{p_2/(1-p_2)}
\]</span></p>
<ul>
<li>Log-odds-ratios can take values from <span class="math inline">\(-\infty\)</span> to <span class="math inline">\(\infty\)</span>.</li>
<li>A value of 0 indicates no association between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>.</li>
<li>Deviations from 0 indicate stronger association between the variables, and deviations are now symmetric; a log-odds-ratio of -0.2 indicates the same <em>strength</em> as 0.2, just the opposite direction.</li>
</ul>
<p>To obtain a confidence interval for the odds-ratio, we work with the log-odds ratio and then exponentiate the resulting interval. Here are the steps:</p>
<ol type="1">
<li>The sample data in a 2x2 table can be labelled as <span class="math inline">\(n_{11}, n_{12}, n_{21}, n_{22}\)</span>.</li>
<li>The <em>sample</em> odds ratio is <span class="math display">\[
\widehat{OR} = \frac{n_{11} \times n_{22}}{n_{12} \times n_{21}}
\]</span></li>
<li>For a large sample size, it can be shown that <span class="math inline">\(\log \widehat{OR}\)</span> follows a Normal distribution. Hence a 95% confidence interval can be obtained through <span class="math display">\[
\log \frac{n_{11} \times n_{22}}{n_{12} \times n_{21}} \pm z_{0.025}
\times ASE(\log \widehat{OR})
\]</span></li>
</ol>
<p>where</p>
<ul>
<li>the ASE (Asymptotic Standard Error) of the estimator is <span class="math display">\[
\sqrt{\frac{1}{n_{11}} + \frac{1}{n_{12}} + \frac{1}{n_{21}} + \frac{1}{n_{22}}}
\]</span></li>
</ul>
<div id="exm-chest-pain-4" class="theorem example" style="background-color: #D5D1D1; padding: 20px">
<p><span class="theorem-title"><strong>Example 4.6 (Chest Pain and Gender Odds Ratio)</strong></span> </p>
<p>Let us compute the confidence interval for the odds ratio in the chest pain and gender example from earlier.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-4-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-1" role="tab" aria-controls="tabset-4-1" aria-selected="true">R code</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-2" role="tab" aria-controls="tabset-4-2" aria-selected="false">Python code</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-4-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a><span class="fu">library</span>(DescTools)</span>
<span id="cb20-2"><a href="#cb20-2"></a><span class="fu">OddsRatio</span>(chest_tab,<span class="at">conf.level =</span> .<span class="dv">95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>odds ratio     lwr.ci     upr.ci 
 1.3534040  0.8626023  2.1234612 </code></pre>
</div>
</div>
</div>
<div id="tabset-4-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb22-2"><a href="#cb22-2"></a>chest_tab2 <span class="op">=</span> sm.stats.Table2x2(chest_array)</span>
<span id="cb22-3"><a href="#cb22-3"></a></span>
<span id="cb22-4"><a href="#cb22-4"></a><span class="bu">print</span>(chest_tab2.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Estimate   SE   LCB    UCB  p-value
--------------------------------------------------
Odds ratio        1.353        0.863 2.123   0.188
Log odds ratio    0.303 0.230 -0.148 0.753   0.188
Risk ratio        1.322        0.872 2.004   0.188
Log risk ratio    0.279 0.212 -0.137 0.695   0.188
--------------------------------------------------</code></pre>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="for-ordinal-variables" class="level3">
<h3 class="anchored" data-anchor-id="for-ordinal-variables">For Ordinal Variables</h3>
<p>When both variables are ordinal, it is often useful to compute the strength (or lack) of any monotone trend association. It allows us to assess if</p>
<blockquote class="blockquote">
<p>As the level of <span class="math inline">\(X\)</span> increases, responses on <span class="math inline">\(Y\)</span> tend to increase toward higher levels, or responses on <span class="math inline">\(Y\)</span> tend to decrease towards lower levels.</p>
</blockquote>
<p>For instance, perhaps job satisfaction tends to increase as income does. In this section, we shall discuss a measure for ordinal variables, analogous to Pearson’s correlation for quantitative variables, that describes the degree to which the relationship is monotone. It is based on the idea of a concordant or discordant pair of subjects.</p>
<div id="def-con-dis-1" class="theorem definition" style="background-color: #D5D1D1; padding: 20px">
<p><span class="theorem-title"><strong>Definition 4.1</strong></span> &nbsp;</p>
<ul>
<li>A <strong>pair of subjects</strong> is <em>concordant</em> if the subject ranked higher on <span class="math inline">\(X\)</span> also ranks higher on <span class="math inline">\(Y\)</span>.</li>
<li>A <strong>pair</strong> is <em>discordant</em> if the subject ranking higher on <span class="math inline">\(X\)</span> ranks lower on <span class="math inline">\(Y\)</span>.</li>
<li>A <strong>pair</strong> is <em>tied</em> if the subjects have the same classification on <span class="math inline">\(X\)</span> and/or <span class="math inline">\(Y\)</span>.</li>
</ul>
</div>
<p>If we let</p>
<ul>
<li><span class="math inline">\(C\)</span>: number of concordant pairs in a dataset, and</li>
<li><span class="math inline">\(D\)</span>: number of discordant pairs in a dataset.</li>
</ul>
<p>Then if <span class="math inline">\(C\)</span> is much larger than <span class="math inline">\(D\)</span>, we would have reason to believe that there is a strong positive association between the two variables. Here are two measures of association based on <span class="math inline">\(C\)</span> and <span class="math inline">\(D\)</span>:</p>
<ol type="1">
<li>Goodman-Kruskal <span class="math inline">\(\gamma\)</span> is computed as <span class="math display">\[
\gamma = \frac{C - D}{C + D}
\]</span></li>
<li>Kendall <span class="math inline">\(\tau_b\)</span> is <span class="math display">\[
\tau_b = \frac{C - D}{A}
\]</span> where <span class="math inline">\(A\)</span> is a normalising constant that results in a measure that works better with ties, and is less sensitive than <span class="math inline">\(\gamma\)</span> to the cut-points defining the categories. <span class="math inline">\(\gamma\)</span> has the advantage that it is more easily interpretable.</li>
</ol>
<p>For both measures, values close to 0 indicate a very weak trend, while values close to 1 (or -1) indicate a strong positive (negative) association.</p>
<div id="exm-job-income-1" class="theorem example" style="background-color: #D5D1D1; padding: 20px">
<p><span class="theorem-title"><strong>Example 4.7 (Job Satisfaction by Income)</strong></span> </p>
<p>Consider the following table, obtained from <span class="citation" data-cites="agresti2012categorical">Agresti (<a href="references.html#ref-agresti2012categorical" role="doc-biblioref">2012</a>)</span>. The original data come from a nationwide survey conducted in the US in 1996.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-5-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-1" role="tab" aria-controls="tabset-5-1" aria-selected="true">R code</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-2" role="tab" aria-controls="tabset-5-2" aria-selected="false">Python code</a></li></ul>
<div class="tab-content">
<div id="tabset-5-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-5-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a>x <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">10</span>, <span class="dv">6</span>,</span>
<span id="cb24-2"><a href="#cb24-2"></a>              <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">10</span>, <span class="dv">7</span>,</span>
<span id="cb24-3"><a href="#cb24-3"></a>              <span class="dv">1</span>, <span class="dv">6</span>, <span class="dv">14</span>, <span class="dv">12</span>,</span>
<span id="cb24-4"><a href="#cb24-4"></a>              <span class="dv">0</span>, <span class="dv">1</span>,  <span class="dv">9</span>, <span class="dv">11</span>), <span class="at">ncol=</span><span class="dv">4</span>, <span class="at">byrow=</span><span class="cn">TRUE</span>)</span>
<span id="cb24-5"><a href="#cb24-5"></a><span class="fu">dimnames</span>(x) <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="fu">c</span>(<span class="st">"&lt;15,000"</span>, <span class="st">"15,000-25,000"</span>, <span class="st">"25,000-40,000"</span>, <span class="st">"&gt;40,000"</span>), </span>
<span id="cb24-6"><a href="#cb24-6"></a>                    <span class="fu">c</span>(<span class="st">"Very Dissat."</span>, <span class="st">"Little Dissat."</span>, <span class="st">"Mod. Sat."</span>, <span class="st">"Very Sat."</span>))</span>
<span id="cb24-7"><a href="#cb24-7"></a>us_svy_tab <span class="ot">&lt;-</span> <span class="fu">as.table</span>(x)</span>
<span id="cb24-8"><a href="#cb24-8"></a></span>
<span id="cb24-9"><a href="#cb24-9"></a>output <span class="ot">&lt;-</span> <span class="fu">Desc</span>(x, <span class="at">plotit =</span> <span class="cn">FALSE</span>, <span class="at">verbose =</span> <span class="dv">3</span>)</span>
<span id="cb24-10"><a href="#cb24-10"></a>output[[<span class="dv">1</span>]]<span class="sc">$</span>assocs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                       estimate  lwr.ci  upr.ci
Contingency Coeff.       0.2419       -       -
Cramer V                 0.1439  0.0000  0.1693
Kendall Tau-b            0.1524 -0.0083  0.3130
Goodman Kruskal Gamma    0.2211 -0.0085  0.4507
Stuart Tau-c             0.1395 -0.0082  0.2871
Somers D C|R             0.1417 -0.0080  0.2915
Somers D R|C             0.1638 -0.0116  0.3392
Pearson Correlation      0.1772 -0.0241  0.3647
Spearman Correlation     0.1769 -0.0245  0.3645
Lambda C|R               0.0377  0.0000  0.2000
Lambda R|C               0.0159  0.0000  0.0693
Lambda sym               0.0259  0.0000  0.1056
Uncertainty Coeff. C|R   0.0311 -0.0076  0.0699
Uncertainty Coeff. R|C   0.0258 -0.0069  0.0585
Uncertainty Coeff. sym   0.0282 -0.0072  0.0637
Mutual Information       0.0508       -       -</code></pre>
</div>
</div>
</div>
<div id="tabset-5-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb26-2"><a href="#cb26-2"></a></span>
<span id="cb26-3"><a href="#cb26-3"></a>us_svy_tab <span class="op">=</span> np.array([[<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">10</span>, <span class="dv">6</span>], </span>
<span id="cb26-4"><a href="#cb26-4"></a>                      [<span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">10</span>, <span class="dv">7</span>],</span>
<span id="cb26-5"><a href="#cb26-5"></a>                      [<span class="dv">1</span>, <span class="dv">6</span>, <span class="dv">14</span>, <span class="dv">12</span>],</span>
<span id="cb26-6"><a href="#cb26-6"></a>                      [<span class="dv">0</span>, <span class="dv">1</span>,  <span class="dv">9</span>, <span class="dv">11</span>]])</span>
<span id="cb26-7"><a href="#cb26-7"></a></span>
<span id="cb26-8"><a href="#cb26-8"></a>dim1 <span class="op">=</span> us_svy_tab.shape</span>
<span id="cb26-9"><a href="#cb26-9"></a>x <span class="op">=</span> []<span class="op">;</span> y<span class="op">=</span>[]</span>
<span id="cb26-10"><a href="#cb26-10"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>, dim1[<span class="dv">0</span>]):</span>
<span id="cb26-11"><a href="#cb26-11"></a>    <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>, dim1[<span class="dv">1</span>]):</span>
<span id="cb26-12"><a href="#cb26-12"></a>        <span class="cf">for</span> k <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>, us_svy_tab[i,j]):</span>
<span id="cb26-13"><a href="#cb26-13"></a>            x.append(i)</span>
<span id="cb26-14"><a href="#cb26-14"></a>            y.append(j)</span>
<span id="cb26-15"><a href="#cb26-15"></a></span>
<span id="cb26-16"><a href="#cb26-16"></a>stats.kendalltau(x, y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>SignificanceResult(statistic=np.float64(0.15235215134659688), pvalue=np.float64(0.0860294855671433))</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>The output shows that both <span class="math inline">\(\gamma = 0.22\)</span> and <span class="math inline">\(\tau_b =0.15\)</span> are close to significant. The lower confidence limit is close to being positive.</p>
</div>
</section>
</section>
<section id="visualisations" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="visualisations"><span class="header-section-number">4.5</span> Visualisations</h2>
<section id="bar-charts" class="level3">
<h3 class="anchored" data-anchor-id="bar-charts">Bar charts</h3>
<p>A common method for visualisation cross combinations of categorical data is to use a bar chart.</p>
<div id="exm-pol-assoc-3" class="theorem example" style="background-color: #D5D1D1; padding: 20px">
<p><span class="theorem-title"><strong>Example 4.8 (Political Association and Gender Barchart)</strong></span> </p>
<p>Here is the R code to make the barchart for the political affiliations data, directly from the contingency table in <a href="#exm-pol-assoc-1" class="quarto-xref">Example&nbsp;<span>4.5</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1"></a><span class="fu">library</span>(lattice)</span>
<span id="cb28-2"><a href="#cb28-2"></a><span class="fu">barchart</span>(political_tab<span class="sc">/</span><span class="fu">rowSums</span>(political_tab), </span>
<span id="cb28-3"><a href="#cb28-3"></a>         <span class="at">horizontal =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="04-categorical_data_analysis_files/figure-html/r-pol-3-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:65.0%"></p>
</figure>
</div>
</div>
</div>
<p>However, the downside is that it does not reflect that the marginal count for males was much less than that for females.</p>
</div>
<p>Let us turn to making bar charts with pandas and Python. We shall use the table from the Claritin example earlier in <a href="#exm-claritin-1" class="quarto-xref">Example&nbsp;<span>4.4</span></a>:</p>
<div id="exm-claritin-2" class="theorem example" style="background-color: #D5D1D1; padding: 20px">
<p><span class="theorem-title"><strong>Example 4.9 (Claritin and Nervousness Barchart)</strong></span> </p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1"></a>claritin_prop <span class="op">=</span> claritin_tab<span class="op">/</span>claritin_tab.<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">1</span>).reshape((<span class="dv">2</span>,<span class="dv">1</span>))</span>
<span id="cb29-2"><a href="#cb29-2"></a></span>
<span id="cb29-3"><a href="#cb29-3"></a>xx <span class="op">=</span> pd.DataFrame(claritin_prop, </span>
<span id="cb29-4"><a href="#cb29-4"></a>                  columns<span class="op">=</span>[<span class="st">'nervous'</span>, <span class="st">'not_nervous'</span>], </span>
<span id="cb29-5"><a href="#cb29-5"></a>                  index<span class="op">=</span>[<span class="st">'claritin'</span>, <span class="st">'placebo'</span>])</span>
<span id="cb29-6"><a href="#cb29-6"></a></span>
<span id="cb29-7"><a href="#cb29-7"></a>xx.plot(kind<span class="op">=</span><span class="st">'bar'</span>, stacked<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="04-categorical_data_analysis_files/figure-html/py-claritin-2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:65.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="mosaic-plots" class="level3">
<h3 class="anchored" data-anchor-id="mosaic-plots">Mosaic plots</h3>
<p>Unlike a bar chart, a mosaic plot reflects the count in each cell (through the area), along with the proportions of interest. Let us inspect how we can make mosaic plots for the political association data earlier.</p>
<div id="exm-pol-assoc-2" class="theorem example" style="background-color: #D5D1D1; padding: 20px">
<p><span class="theorem-title"><strong>Example 4.10 (Political Association and Gender Mosaic Plot)</strong></span> </p>
<p>The colours in the output for the R code reflect the sizes of the standardised residuals displayed below <a href="#exm-pol-assoc-1" class="quarto-xref">Example&nbsp;<span>4.5</span></a>.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-6-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-1" role="tab" aria-controls="tabset-6-1" aria-selected="true">R code</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-6-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-2" role="tab" aria-controls="tabset-6-2" aria-selected="false">Python code</a></li></ul>
<div class="tab-content">
<div id="tabset-6-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-6-1-tab">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1"></a><span class="fu">mosaicplot</span>(political_tab, <span class="at">shade=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="04-categorical_data_analysis_files/figure-html/r-pol-4-3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:65.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-6-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-6-2-tab">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1"></a><span class="im">from</span> statsmodels.graphics.mosaicplot <span class="im">import</span> mosaic</span>
<span id="cb31-2"><a href="#cb31-2"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb31-3"><a href="#cb31-3"></a></span>
<span id="cb31-4"><a href="#cb31-4"></a>political_tab <span class="op">=</span> np.asarray([[<span class="dv">762</span>,<span class="dv">327</span>,<span class="dv">468</span>], [<span class="dv">484</span>,<span class="dv">239</span>,<span class="dv">477</span>]])</span>
<span id="cb31-5"><a href="#cb31-5"></a>mosaic(political_tab, statistic<span class="op">=</span><span class="va">True</span>, gap<span class="op">=</span><span class="fl">0.05</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="04-categorical_data_analysis_files/figure-html/py-pol-4-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:65.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="conditional-density-plots" class="level3">
<h3 class="anchored" data-anchor-id="conditional-density-plots">Conditional Density Plots</h3>
<p>When we have one categorical and one quantitative variable, the kind of plot we make really depends on which is the response, and which is the explanatory variable. If the response variable is the quantitative one, it makes sense to create boxplots or histograms. However, if the response variable is a the categorical one, we should really be making something along these lines:</p>
<div id="exm-heart-1" class="theorem example" style="background-color: #D5D1D1; padding: 20px">
<p><span class="theorem-title"><strong>Example 4.11</strong></span> </p>
<p>The dataset at <a href="https://archive.ics.uci.edu/dataset/519/heart+failure+clinical+records">UCI repository</a> contains records on 299 patients who had heart failure. The data was collected during the follow-up period; each patient had 13 clinical features recorded. The primary variable of interest was whether they died or not. Suppose we wished to plot how this varied with age (a quantitative variable):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1"></a>heart_failure <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/heart+failure+clinical+records/heart_failure_clinical_records_dataset.csv"</span>)</span>
<span id="cb32-2"><a href="#cb32-2"></a><span class="fu">spineplot</span>(<span class="fu">as.factor</span>(DEATH_EVENT) <span class="sc">~</span> age, <span class="at">data=</span>heart_failure)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="04-categorical_data_analysis_files/figure-html/r-cd-1-3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:65.0%"></p>
</figure>
</div>
</div>
</div>
<p>It reflects how the probability of an event varies with the quantitative explanatory variable. A smoothed version of this is known as the conditional density plot:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1"></a><span class="fu">cdplot</span>(<span class="fu">as.factor</span>(DEATH_EVENT) <span class="sc">~</span> age, <span class="at">data=</span>heart_failure)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="04-categorical_data_analysis_files/figure-html/r-cd-2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:65.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="further-readings" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="further-readings"><span class="header-section-number">4.6</span> Further readings</h2>
<p>In general, I have found that R packages seem to have a lot more measures of association for categorical variables. In Python, the measures are spread out across packages.</p>
<p>Above, we have only scratched the surface of what is available. If you are keen, do read up on</p>
<ol type="1">
<li>Somer’s D (for association between nominal and ordinal)</li>
<li>Mutual Information (for association between all types of pairs of categorical variables)</li>
<li>Polychoric correlation (for association between two ordinal variables)</li>
</ol>
<p>Also, take note of how log odds ratios, <span class="math inline">\(\tau_b\)</span> and <span class="math inline">\(\gamma\)</span> work - they range between -1 to 1 (in general), and values close to 0 reflect weak association. Values of <span class="math inline">\(a\)</span> and <span class="math inline">\(-a\)</span> indicate the same <em>strength</em>, but different direction of association. This allows the same intuition that Pearson’s correlation does. When you are presented with new metrics, try to understand them by asking similar questions about them.</p>
</section>
<section id="references" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="references"><span class="header-section-number">4.7</span> References</h2>
<section id="website-references" class="level3">
<h3 class="anchored" data-anchor-id="website-references">Website References</h3>
<ol type="1">
<li>Documentation pages from statsmodels:
<ul>
<li><a href="https://www.statsmodels.org/stable/generated/statsmodels.graphics.mosaicplot.mosaic.html#statsmodels.graphics.mosaicplot.mosaic">Mosaic plots</a></li>
<li><a href="https://www.statsmodels.org/stable/contingency_tables.html#module-statsmodels.stats.contingency_tables">Contingency tables</a></li>
</ul></li>
<li>Documentation pages from scipy:
<ul>
<li><a href="https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.fisher_exact.html">Fisher test with scipy</a></li>
<li><a href="https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.chi2_contingency.html"><span class="math inline">\(\chi^2\)</span>-test</a></li>
</ul></li>
<li><a href="https://archive.ics.uci.edu/dataset/519/heart+failure+clinical+records">Heart failure data</a></li>
<li><a href="https://online.stat.psu.edu/stat509/lesson/18/18.3">More information on Kendall <span class="math inline">\(\tau_b\)</span> statistic</a></li>
<li>The <span class="math inline">\(\chi^2\)</span> test we studied is a <em>test of independence</em>. It is a variant of the <span class="math inline">\(\chi^2\)</span> goodness-of-fit test, which is used to assess if data come from a particular distribution. It’s just in our case, the presumed distribution is one with independence between the groups. Read more about the <a href="https://stats.libretexts.org/Bookshelves/Introductory_Statistics/Introductory_Statistics_(Shafer_and_Zhang)/11%3A_Chi-Square_Tests_and_F-Tests/11.02%3A_Chi-Square_One-Sample_Goodness-of-Fit_Tests">goodness-of-fit test here</a>.</li>
</ol>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-agresti2012categorical" class="csl-entry" role="listitem">
Agresti, Alan. 2012. <em>Categorical Data Analysis</em>. Vol. 792. John Wiley &amp; Sons.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./03-summarising_data.html" class="pagination-link" aria-label="Summarising Numerical Data">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Summarising Numerical Data</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./05-robust_statistics.html" class="pagination-link" aria-label="Robust Statistics">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Robust Statistics</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>