<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.549">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistical Computing and Programming - 8&nbsp; ANOVA</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./09-regression.html" rel="next">
<link href="./07-2_sample_tests.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./08-anova.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">ANOVA</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistical Computing and Programming</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro_to_R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-intro_to_python.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction to Python</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-summarising_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Exploring Quantitative Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-categorical_data_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Exploring Categorical Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-robust_statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Robust Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-intro_to_sas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Introduction to SAS</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-2_sample_tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Two-sample Hypothesis Tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-anova.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Simulation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Academic References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contents</h2>
   
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">8.1</span> Introduction</a></li>
  <li><a href="#one-way-analysis-of-variance" id="toc-one-way-analysis-of-variance" class="nav-link" data-scroll-target="#one-way-analysis-of-variance"><span class="header-section-number">8.2</span> One-Way Analysis of Variance</a></li>
  <li><a href="#sec-spec-grps" id="toc-sec-spec-grps" class="nav-link" data-scroll-target="#sec-spec-grps"><span class="header-section-number">8.3</span> Comparing specific groups</a></li>
  <li><a href="#contrast-estimation" id="toc-contrast-estimation" class="nav-link" data-scroll-target="#contrast-estimation"><span class="header-section-number">8.4</span> Contrast Estimation</a></li>
  <li><a href="#multiple-comparisons" id="toc-multiple-comparisons" class="nav-link" data-scroll-target="#multiple-comparisons"><span class="header-section-number">8.5</span> Multiple Comparisons</a></li>
  <li><a href="#kruskal-wallis-procedure" id="toc-kruskal-wallis-procedure" class="nav-link" data-scroll-target="#kruskal-wallis-procedure"><span class="header-section-number">8.6</span> Kruskal-Wallis Procedure</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">8.7</span> Summary</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">8.8</span> References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">ANOVA</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">8.1</span> Introduction</h2>
<p>In the previous topic, we learned how to run two-sample <span class="math inline">\(t\)</span>-tests. The objective of these procedures is to compare the means from two groups. Frequently, however, the means of more than two groups need to be compared.</p>
<p>In this topic, we introduce the <em>one-way analysis of variance</em> (ANOVA), which generalises the <span class="math inline">\(t\)</span>-test methodology to more than 2 groups. Hypothesis tests in the ANOVA framework require the assumption of Normality. When this does not hold, we turn to the Kruskal-Wallis test - the non-parametric version, to compare distributions between groups.</p>
<p>While the <span class="math inline">\(F\)</span>-test in ANOVA provides a determination of whether or not the group means are different, in practice, we would always want to follow up with specific comparisons between groups as well. This topic covers how we can construct confidence intervals in those cases as well.</p>
<div id="exm-antibiotics-1" class="theorem example" style="background-color: #D5D1D1; padding: 20px">
<p><span class="theorem-title"><strong>Example 8.1 (Effect of Antibiotics)</strong></span> </p>
<p>The following example was taken from <span class="citation" data-cites="ekstrom2015statistical">Ekstrøm and Sørensen (<a href="references.html#ref-ekstrom2015statistical" role="doc-biblioref">2015</a>)</span>. An experiment with dung from heifers<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> was carried out in order to explore the influence of antibiotics on the decomposition of dung organic material. As part of the experiment, 36 heifers were randomly assigned into six groups.</p>
<p>Antibiotics of different types were added to the feed for heifers in five of the groups. The remaining group served as a control group. For each heifer, a bag of dung was dug into the soil, and after 8 weeks the amount of organic material was measured for each bag.</p>
<p><a href="#fig-heifers-bp" class="quarto-xref">Figure&nbsp;<span>8.1</span></a> contains a boxplot of the data from each group.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-heifers-bp" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-heifers-bp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08-anova_files/figure-html/fig-heifers-bp-1.png" id="fig-heifers-bp" class="img-fluid quarto-figure quarto-figure-center anchored figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-heifers-bp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.1
</figcaption>
</figure>
</div>
</div>
</div>
<p>Compared to the control group, it does appear that the median organic weight of the dung from the other heifer groups is higher. The following table displays the mean, standard deviation, and count from each group:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>      type  mean    sd count
1  Control 2.603 0.119     6
2  Alfacyp 2.895 0.117     6
3 Enroflox 2.710 0.162     6
4 Fenbenda 2.833 0.124     6
5 Ivermect 3.002 0.109     6
6 Spiramyc 2.855 0.054     4</code></pre>
</div>
</div>
<p>Observe that the Spiramycin group only yielded 4 readings instead of 6. Our goal in this topic is to apply a technique for assessing if group means are statistically different from one another. Here are the specific analyses that we shall carry out:</p>
<ol type="1">
<li>Is there any significant difference, at 5% level, between the mean decomposition level of the groups?</li>
<li>At 5% level, is the mean level for Enrofloxacin different from the control group?</li>
<li>Pharmacologically speaking, Ivermectin and Fenbendazole are similar to each other. Let us call this sub-group (A). They work differently than Enrofloxacin. At 5% level, is there a significant difference between the mean from sub-group A and Enrofloxacin?</li>
</ol>
</div>
</section>
<section id="one-way-analysis-of-variance" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="one-way-analysis-of-variance"><span class="header-section-number">8.2</span> One-Way Analysis of Variance</h2>
<section id="formal-set-up" class="level3">
<h3 class="anchored" data-anchor-id="formal-set-up">Formal Set-up</h3>
<p>Suppose there are <span class="math inline">\(k\)</span> groups with <span class="math inline">\(n_i\)</span> observations in the <span class="math inline">\(i\)</span>-th group. The <span class="math inline">\(j\)</span>-th observation in the <span class="math inline">\(i\)</span>-th group will be denoted by <span class="math inline">\(Y_{ij}\)</span>. In the One-Way ANOVA, we assume the following model:</p>
<p><span class="math display">\[\begin{equation}
Y_{ij}  = \mu + \alpha_i + e_{ij},\; i=1,\ldots,k,\; j=1,\ldots,n_i
\end{equation}\]</span></p>
<ul>
<li><span class="math inline">\(\mu\)</span> is a constant, representing the underlying mean of all groups taken together.</li>
<li><span class="math inline">\(\alpha_i\)</span> is a constant specific to the <span class="math inline">\(i\)</span>-th group. It represents the difference between the mean of the <span class="math inline">\(i\)</span>-th group and the overall mean.</li>
<li><span class="math inline">\(e_{ij}\)</span> represents random error about the mean <span class="math inline">\(\mu + \alpha_i\)</span> for an individual observation from the <span class="math inline">\(i\)</span>-th group.</li>
</ul>
<p>In terms of distributions, we assume that the <span class="math inline">\(e_{ij}\)</span> are i.i.d from a Normal distribution with mean 0 and variance <span class="math inline">\(\sigma^2\)</span>. This leads to the model for each observation:</p>
<p><span id="eq-yij"><span class="math display">\[
Y_{ij} \sim N(\mu + \alpha_i,\; \sigma^2)
\tag{8.1}\]</span></span></p>
<p>It is not possible to estimate both <span class="math inline">\(\mu\)</span> and all the <span class="math inline">\(k\)</span> different <span class="math inline">\(\alpha_i\)</span>’s, since we only have <span class="math inline">\(k\)</span> observed mean values for the <span class="math inline">\(k\)</span> groups. For identifiability purposes, we need to constrain the parameters. There are two common constraints used, and note that different software have different defaults:</p>
<ol type="1">
<li>Setting <span class="math inline">\(\sum_{i=1}^k \alpha_i = 0\)</span>, or</li>
<li>Setting <span class="math inline">\(\alpha_1= 0\)</span>.</li>
</ol>
<p>Continuing on from <a href="#eq-yij" class="quarto-xref">Equation&nbsp;<span>8.1</span></a>, let us denote the mean for the <span class="math inline">\(i\)</span>-th group as <span class="math inline">\(\overline{Y_i}\)</span>, and the overall mean of all observations as <span class="math inline">\(\overline{\overline{Y}}\)</span>. We can then write the deviation of an individual observation from the overall mean as:</p>
<p><span id="eq-y-dev"><span class="math display">\[
Y_{ij} - \overline{\overline{Y}} = \underbrace{(Y_{ij} - \overline{Y_i})}_{\text{within}} +
\underbrace{(\overline{Y_i} - \overline{\overline{Y}})}_{\text{between}}
\tag{8.2}\]</span></span></p>
<p>The first term on the right of the above equation is the source of <em>within-group variability</em>. The second term on the right gives rise to <em>between-group variability</em>. The intuition behind the ANOVA procedure is that if the between-group variability is large and the within-group variability is small, then we have evidence that the group means are different.</p>
<p>If we square both sides of <a href="#eq-y-dev" class="quarto-xref">Equation&nbsp;<span>8.2</span></a> and sum over all observations, we arrive at the following equation; the essence of ANOVA:</p>
<p><span class="math display">\[
\sum_{i=1}^k \sum_{j=1}^{n_i} \left( Y_{ij} - \overline{\overline{Y}} \right)^2 =
\sum_{i=1}^k \sum_{j=1}^{n_i} \left( Y_{ij} - \overline{Y_i} \right)^2 +
\sum_{i=1}^k \sum_{j=1}^{n_i} \left( \overline{Y_i} -
                                     \overline{\overline{Y}} \right)^2
\]</span></p>
<p>The squared sums above are referred to as: <span class="math display">\[
SS_T = SS_W + SS_B
\]</span></p>
<ul>
<li><span class="math inline">\(SS_T\)</span>: Sum of Squares Total,</li>
<li><span class="math inline">\(SS_W\)</span>: Sum of Squares Within, and</li>
<li><span class="math inline">\(SS_B\)</span>: Sum of Squares Between.</li>
</ul>
<p>In addition the following definitions are important for understanding the ANOVA output:</p>
<ol type="1">
<li>The Between Mean Square: <span class="math display">\[
MS_B = \frac{SS_B}{k-1}
\]</span></li>
<li>The Within Mean Square: <span class="math display">\[
MS_W = \frac{SS_W}{n - k}
\]</span></li>
</ol>
<p>The mean squares are estimates of the variability between and within groups. The ratio of these quantities is the test statistic.</p>
</section>
<section id="f-test-in-one-way-anova" class="level3">
<h3 class="anchored" data-anchor-id="f-test-in-one-way-anova"><span class="math inline">\(F\)</span>-Test in One-Way ANOVA</h3>
<p>The null and alternative hypotheses are:</p>
<p><span class="math display">\[\begin{eqnarray*}
H_0 &amp;:&amp; \alpha_i = 0 \text{ for all } i \\
H_1 &amp;:&amp; \alpha_i \ne 0 \text{ for at least one } i
\end{eqnarray*}\]</span></p>
<p>The test statistic is given by <span class="math display">\[
F = \frac{MS_B}{MS_W}
\]</span></p>
<p>Under <span class="math inline">\(H_0\)</span>, the statistic <span class="math inline">\(F\)</span> follows an <span class="math inline">\(F\)</span> distribution with <span class="math inline">\(k-1\)</span> and <span class="math inline">\(n-k\)</span> degrees of freedom.</p>
</section>
<section id="assumptions" class="level3">
<h3 class="anchored" data-anchor-id="assumptions">Assumptions</h3>
<p>These are the assumptions that will need to be validated.</p>
<ol type="1">
<li>The observations are independent of each other. This is usually a characteristic of the design of the experiment, and is not something we can always check from the data.</li>
<li>The errors are Normally distributed. Residuals can be calculated as follows: <span class="math display">\[
Y_{ij} - \overline{Y_i}
\]</span> The distribution of these residuals should be checked for Normality.</li>
<li>The variance within each group is the same. In ANOVA, the <span class="math inline">\(MS_W\)</span> is a pooled estimate (across the groups) that is used; in order for this to be valid, the variance within each group should be identical. As in the 2-sample situation, we shall avoid separate hypotheses tests and proceed with the rule-of-thumb that if the ratio of the largest to smallest standard deviation is less than 2, we can proceed with the analysis.</li>
</ol>
<div id="exm-antibiotics-2" class="theorem example" style="background-color: #D5D1D1; padding: 20px">
<p><span class="theorem-title"><strong>Example 8.2 (F-test)</strong></span> </p>
<p>We being by applying the overall <span class="math inline">\(F\)</span>-test to the heifers data, to assess if there is any significant difference between the means.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true">R code</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Python code</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false">SAS output</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="co">#R </span></span>
<span id="cb2-2"><a href="#cb2-2"></a>heifers <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/antibio.csv"</span>)</span>
<span id="cb2-3"><a href="#cb2-3"></a>u_levels <span class="ot">&lt;-</span> <span class="fu">sort</span>(<span class="fu">unique</span>(heifers<span class="sc">$</span>type))</span>
<span id="cb2-4"><a href="#cb2-4"></a>heifers<span class="sc">$</span>type <span class="ot">&lt;-</span> <span class="fu">factor</span>(heifers<span class="sc">$</span>type, </span>
<span id="cb2-5"><a href="#cb2-5"></a>                       <span class="at">levels=</span>u_levels[<span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>)])</span>
<span id="cb2-6"><a href="#cb2-6"></a>heifers_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(org <span class="sc">~</span> type, <span class="at">data=</span>heifers)</span>
<span id="cb2-7"><a href="#cb2-7"></a><span class="fu">anova</span>(heifers_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: org
          Df  Sum Sq  Mean Sq F value    Pr(&gt;F)    
type       5 0.59082 0.118165  7.9726 8.953e-05 ***
Residuals 28 0.41500 0.014821                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1"></a><span class="co">#Python</span></span>
<span id="cb4-2"><a href="#cb4-2"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb4-3"><a href="#cb4-3"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb4-4"><a href="#cb4-4"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb4-5"><a href="#cb4-5"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb4-6"><a href="#cb4-6"></a><span class="im">from</span> statsmodels.formula.api <span class="im">import</span> ols</span>
<span id="cb4-7"><a href="#cb4-7"></a></span>
<span id="cb4-8"><a href="#cb4-8"></a>heifers <span class="op">=</span> pd.read_csv(<span class="st">"data/antibio.csv"</span>)</span>
<span id="cb4-9"><a href="#cb4-9"></a>heifer_lm <span class="op">=</span> ols(<span class="st">'org ~ type'</span>, data<span class="op">=</span>heifers).fit()</span>
<span id="cb4-10"><a href="#cb4-10"></a>anova_tab <span class="op">=</span> sm.stats.anova_lm(heifer_lm, <span class="bu">type</span><span class="op">=</span><span class="dv">3</span>,)</span>
<span id="cb4-11"><a href="#cb4-11"></a><span class="bu">print</span>(anova_tab)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            df    sum_sq   mean_sq         F   PR(&gt;F)
type       5.0  0.590824  0.118165  7.972558  0.00009
Residual  28.0  0.415000  0.014821       NaN      NaN</code></pre>
</div>
</div>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/sas_anova_f_test.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p>At the 5% significance level, we reject the null hypothesis to conclude that the group means are significantly different from one another. This answers question (1) from <a href="#exm-antibiotics-1" class="quarto-xref">Example&nbsp;<span>8.1</span></a>.</p>
<p>To extract the estimated parameters, we can use the following code:</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true">R code</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false">Python code</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-3" role="tab" aria-controls="tabset-2-3" aria-selected="false">SAS output</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a><span class="co"># R</span></span>
<span id="cb6-2"><a href="#cb6-2"></a><span class="fu">summary</span>(heifers_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = org ~ type, data = heifers)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.29000 -0.06000  0.01833  0.07250  0.18667 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   2.60333    0.04970  52.379  &lt; 2e-16 ***
typeAlfacyp   0.29167    0.07029   4.150 0.000281 ***
typeEnroflox  0.10667    0.07029   1.518 0.140338    
typeFenbenda  0.23000    0.07029   3.272 0.002834 ** 
typeIvermect  0.39833    0.07029   5.667  4.5e-06 ***
typeSpiramyc  0.25167    0.07858   3.202 0.003384 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1217 on 28 degrees of freedom
Multiple R-squared:  0.5874,    Adjusted R-squared:  0.5137 
F-statistic: 7.973 on 5 and 28 DF,  p-value: 8.953e-05</code></pre>
</div>
</div>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1"></a><span class="co"># Python</span></span>
<span id="cb8-2"><a href="#cb8-2"></a><span class="bu">print</span>(heifer_lm.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    org   R-squared:                       0.587
Model:                            OLS   Adj. R-squared:                  0.514
Method:                 Least Squares   F-statistic:                     7.973
Date:                Fri, 20 Dec 2024   Prob (F-statistic):           8.95e-05
Time:                        16:04:37   Log-Likelihood:                 26.655
No. Observations:                  34   AIC:                            -41.31
Df Residuals:                      28   BIC:                            -32.15
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
====================================================================================
                       coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept            2.8950      0.050     58.248      0.000       2.793       2.997
type[T.Control]     -0.2917      0.070     -4.150      0.000      -0.436      -0.148
type[T.Enroflox]    -0.1850      0.070     -2.632      0.014      -0.329      -0.041
type[T.Fenbenda]    -0.0617      0.070     -0.877      0.388      -0.206       0.082
type[T.Ivermect]     0.1067      0.070      1.518      0.140      -0.037       0.251
type[T.Spiramyc]    -0.0400      0.079     -0.509      0.615      -0.201       0.121
==============================================================================
Omnibus:                        2.172   Durbin-Watson:                   2.146
Prob(Omnibus):                  0.338   Jarque-Bera (JB):                1.704
Skew:                          -0.545   Prob(JB):                        0.427
Kurtosis:                       2.876   Cond. No.                         6.71
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
</div>
<div id="tabset-2-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-3-tab">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/sas_anova_heifer_group_means.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p>When estimating, both R and Python set one of the <span class="math inline">\(\alpha_i\)</span> to be equal to 0. In the case of R, it is the coefficient for <code>Control</code>, since we set it as the first level in the factor. For Python, we can tell from the output that the constraint has been placed on the coefficient for <code>Alfacyp</code> (since it is missing).</p>
<p>However, all estimates are group means are identical. From the R output, we can compute that the estimate of the mean for the <code>Alfacyp</code> group is <span class="math display">\[
2.603 + 0.292 = 2.895
\]</span> From the Python output, we can read off (the Intercept term) that the estimate for <code>Alfacyp</code> is precisely <span class="math display">\[
2.895 + 0 = 2.895
\]</span></p>
<p>To check the assumptions, we can use the following code:</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true">R code</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false">Python code</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a><span class="co"># R</span></span>
<span id="cb10-2"><a href="#cb10-2"></a>r1 <span class="ot">&lt;-</span> <span class="fu">residuals</span>(heifers_lm)</span>
<span id="cb10-3"><a href="#cb10-3"></a><span class="fu">hist</span>(r1)</span>
<span id="cb10-4"><a href="#cb10-4"></a><span class="fu">qqnorm</span>(r1); <span class="fu">qqline</span>(r1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="08-anova_files/figure-html/r-normality-1.png" class="img-fluid" width="672"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="08-anova_files/figure-html/r-normality-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1"></a><span class="co"># Python</span></span>
<span id="cb11-2"><a href="#cb11-2"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb11-3"><a href="#cb11-3"></a></span>
<span id="cb11-4"><a href="#cb11-4"></a>f, axs <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">8</span>,<span class="dv">4</span>))</span>
<span id="cb11-5"><a href="#cb11-5"></a>tmp <span class="op">=</span> plt.subplot(<span class="dv">121</span>)</span>
<span id="cb11-6"><a href="#cb11-6"></a>heifer_lm.resid.hist()<span class="op">;</span></span>
<span id="cb11-7"><a href="#cb11-7"></a>tmp <span class="op">=</span> plt.subplot(<span class="dv">122</span>)</span>
<span id="cb11-8"><a href="#cb11-8"></a>sm.qqplot(heifer_lm.resid, line<span class="op">=</span><span class="st">"q"</span>, ax<span class="op">=</span>tmp)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="08-anova_files/figure-html/py-normality-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<p>For SAS, we have to create a new column containing the residuals in a temporary dataset before creating these plots.</p>
</div>
</section>
</section>
<section id="sec-spec-grps" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="sec-spec-grps"><span class="header-section-number">8.3</span> Comparing specific groups</h2>
<p>The <span class="math inline">\(F\)</span>-test in a One-Way ANOVA indicates if all means are equal, but does not provide further insight into which particular groups differ. If we had specified beforehand that we wished to test if two particular groups <span class="math inline">\(i_1\)</span> and <span class="math inline">\(i_2\)</span> had different means, we could do so with a t-test. Here are the details to compute a Confidence Interval in this case:</p>
<ol type="1">
<li>Compute the estimate of the difference between the two means: <span class="math display">\[
\overline{Y_{i_1}} - \overline{Y_{i_2}}
\]</span></li>
<li>Compute the standard error of the above estimator: <span class="math display">\[
\sqrt{MS_W \left( \frac{1}{n_{i_1}} + \frac{1}{n_{i_2}} \right) }
\]</span></li>
<li>Compute the <span class="math inline">\(100(1- \alpha)%\)</span> confidence interval as: <span class="math display">\[
\overline{Y_{i_1}} - \overline{Y_{i_2}} \pm
t_{n-k, \alpha/2}  \times
\sqrt{MS_W \left( \frac{1}{n_{i_1}} + \frac{1}{n_{i_2}} \right) }
\]</span></li>
</ol>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you notice from the output in <a href="#exm-antibiotics-1" class="quarto-xref">Example&nbsp;<span>8.1</span></a>, the rule-of-thumb regarding standard deviations has not been satisfied. The ratio of largest to smallest standard deviations is slightly more than 2. Hence we should in fact switch to the non-parametric version of the test; the pooled estimate of the variance may not be valid. However, we shall proceed with this dataset just to demonstrate the next few techniques, instead of introducing a new dataset.</p>
</div>
</div>
<div id="exm-antibiotics-3" class="theorem example" style="background-color: #D5D1D1; padding: 20px">
<p><span class="theorem-title"><strong>Example 8.3 (Enrofloxacin vs.&nbsp;Control)</strong></span> </p>
<p>Let us attempt to answer question (2), that we had set out earlier in <a href="#exm-antibiotics-1" class="quarto-xref">Example&nbsp;<span>8.1</span></a>.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-4-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-1" role="tab" aria-controls="tabset-4-1" aria-selected="true">R code</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-2" role="tab" aria-controls="tabset-4-2" aria-selected="false">Python code</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-3" role="tab" aria-controls="tabset-4-3" aria-selected="false">SAS code</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-4-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a><span class="co"># R </span></span>
<span id="cb12-2"><a href="#cb12-2"></a>summary_out <span class="ot">&lt;-</span> <span class="fu">anova</span>(heifers_lm)</span>
<span id="cb12-3"><a href="#cb12-3"></a>est_coef <span class="ot">&lt;-</span> <span class="fu">coef</span>(heifers_lm)</span>
<span id="cb12-4"><a href="#cb12-4"></a>est1  <span class="ot">&lt;-</span> <span class="fu">unname</span>(est_coef[<span class="dv">3</span>]) <span class="co"># coefficient for Enrofloxacin</span></span>
<span id="cb12-5"><a href="#cb12-5"></a>MSW <span class="ot">&lt;-</span> summary_out<span class="sc">$</span><span class="st">`</span><span class="at">Mean Sq</span><span class="st">`</span>[<span class="dv">2</span>]</span>
<span id="cb12-6"><a href="#cb12-6"></a>df <span class="ot">&lt;-</span> summary_out<span class="sc">$</span>Df[<span class="dv">2</span>]</span>
<span id="cb12-7"><a href="#cb12-7"></a>q1 <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="fl">0.025</span>, df, <span class="dv">0</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb12-8"><a href="#cb12-8"></a></span>
<span id="cb12-9"><a href="#cb12-9"></a>lower_ci <span class="ot">&lt;-</span> est1 <span class="sc">-</span> q1<span class="sc">*</span><span class="fu">sqrt</span>(MSW <span class="sc">*</span> (<span class="dv">1</span><span class="sc">/</span><span class="dv">6</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>))</span>
<span id="cb12-10"><a href="#cb12-10"></a>upper_ci <span class="ot">&lt;-</span> est1 <span class="sc">+</span> q1<span class="sc">*</span><span class="fu">sqrt</span>(MSW <span class="sc">*</span> (<span class="dv">1</span><span class="sc">/</span><span class="dv">6</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>))</span>
<span id="cb12-11"><a href="#cb12-11"></a><span class="fu">cat</span>(<span class="st">"The 95% CI for the diff. between Enrofloxacin and Control is ("</span>,</span>
<span id="cb12-12"><a href="#cb12-12"></a>    <span class="fu">format</span>(lower_ci, <span class="at">digits =</span> <span class="dv">3</span>), <span class="st">","</span>, </span>
<span id="cb12-13"><a href="#cb12-13"></a>    <span class="fu">format</span>(upper_ci, <span class="at">digits =</span> <span class="dv">3</span>), <span class="st">")."</span>, <span class="at">sep=</span><span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The 95% CI for the diff. between Enrofloxacin and Control is (-0.0373,0.251).</code></pre>
</div>
</div>
</div>
<div id="tabset-4-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1"></a><span class="co"># Python</span></span>
<span id="cb14-2"><a href="#cb14-2"></a>est1  <span class="op">=</span> heifer_lm.params.iloc[<span class="dv">2</span>] <span class="op">-</span> heifer_lm.params.iloc[<span class="dv">1</span>]</span>
<span id="cb14-3"><a href="#cb14-3"></a>MSW <span class="op">=</span> heifer_lm.mse_resid</span>
<span id="cb14-4"><a href="#cb14-4"></a>df <span class="op">=</span> heifer_lm.df_resid</span>
<span id="cb14-5"><a href="#cb14-5"></a>q1 <span class="op">=</span> <span class="op">-</span>stats.t.ppf(<span class="fl">0.025</span>, df)</span>
<span id="cb14-6"><a href="#cb14-6"></a></span>
<span id="cb14-7"><a href="#cb14-7"></a>lower_ci <span class="op">=</span> est1 <span class="op">-</span> q1<span class="op">*</span>np.sqrt(MSW <span class="op">*</span> (<span class="dv">1</span><span class="op">/</span><span class="dv">6</span> <span class="op">+</span> <span class="dv">1</span><span class="op">/</span><span class="dv">6</span>))</span>
<span id="cb14-8"><a href="#cb14-8"></a>upper_ci <span class="op">=</span> est1 <span class="op">+</span> q1<span class="op">*</span>np.sqrt(MSW <span class="op">*</span> (<span class="dv">1</span><span class="op">/</span><span class="dv">6</span> <span class="op">+</span> <span class="dv">1</span><span class="op">/</span><span class="dv">6</span>))</span>
<span id="cb14-9"><a href="#cb14-9"></a><span class="bu">print</span>(<span class="ss">f"""The 95% CI for the diff. between Enrofloxacin and control is</span></span>
<span id="cb14-10"><a href="#cb14-10"></a><span class="ss">(</span><span class="sc">{</span>lower_ci<span class="sc">:.3f}</span><span class="ss">, </span><span class="sc">{</span>upper_ci<span class="sc">:.3f}</span><span class="ss">)."""</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The 95% CI for the diff. between Enrofloxacin and control is
(-0.037, 0.251).</code></pre>
</div>
</div>
</div>
<div id="tabset-4-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-3-tab">
<p>In order to get SAS to generate the estimate, modify the code to include <code>clparm</code> in the <code>model</code> statement, and include the <code>estimate</code> statement.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a>proc glm data<span class="ot">=</span>ST2137.HEIFERS;</span>
<span id="cb16-2"><a href="#cb16-2"></a>    class type;</span>
<span id="cb16-3"><a href="#cb16-3"></a>    model org<span class="ot">=</span>type <span class="sc">/</span> clparm;</span>
<span id="cb16-4"><a href="#cb16-4"></a>    means type <span class="sc">/</span> hovtest<span class="ot">=</span>levene welch plots<span class="ot">=</span>none;</span>
<span id="cb16-5"><a href="#cb16-5"></a>    lsmeans type <span class="sc">/</span> adjust<span class="ot">=</span>tukey pdiff alpha<span class="ot">=</span>.<span class="dv">05</span>;</span>
<span id="cb16-6"><a href="#cb16-6"></a>    estimate <span class="st">'enro_vs_control'</span> type <span class="dv">0</span> <span class="sc">-</span><span class="dv">1</span> <span class="dv">1</span> <span class="dv">0</span> <span class="dv">0</span> <span class="dv">0</span>;</span>
<span id="cb16-7"><a href="#cb16-7"></a>    output out<span class="ot">=</span>work.Oneway_stats r<span class="ot">=</span>residual;</span>
<span id="cb16-8"><a href="#cb16-8"></a>    run;</span>
<span id="cb16-9"><a href="#cb16-9"></a>quit;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/sas_anova_heifer_pairwise.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p>As the confidence interval contains the value 0, the binary conclusion would be to not reject the null hypothesis at the 5% level.</p>
</div>
</section>
<section id="contrast-estimation" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="contrast-estimation"><span class="header-section-number">8.4</span> Contrast Estimation</h2>
<p>A more general comparison, such as the comparison of a collection of <span class="math inline">\(l_1\)</span> groups with another collection of <span class="math inline">\(l_2\)</span> groups, is also possible. First, note that a linear contrast is any linear combination of the individual group means such that the linear coefficients add up to 0. In other words, consider <span class="math inline">\(L\)</span> such that</p>
<p><span class="math display">\[
L = \sum_{i=1}^k c_i \overline{Y_i}, \text{ where } \sum_{i=1}^k c_i = 0
\]</span></p>
<p>Note that the comparison of two groups in <a href="#sec-spec-grps" class="quarto-xref"><span>Section 8.3</span></a> is a special case of this linear contrast.</p>
<p>Here is the procedure for computing confidence intervals for a linear contrast:</p>
<ol type="1">
<li>Compute the estimate of the contrast: <span class="math display">\[
L = \sum_{i=1}^k c_i \overline{Y_i}
\]</span></li>
<li>Compute the standard error of the above estimator: <span class="math display">\[
\sqrt{MS_W \sum_{i=1}^k \frac{c_i^2}{n_i} }
\]</span></li>
<li>Compute the <span class="math inline">\(100(1- \alpha)%\)</span> confidence interval as: <span class="math display">\[
L \pm
t_{n-k, \alpha/2}  \times
\sqrt{MS_W \sum_{i=1}^k \frac{c_i^2}{n_i} }
\]</span></li>
</ol>
<div id="exm-antibiotics-4" class="theorem example" style="background-color: #D5D1D1; padding: 20px">
<p><span class="theorem-title"><strong>Example 8.4 (Comparing collection of groups)</strong></span> </p>
<p>Let sub-group 1 consist of Ivermectin and Fenbendazole. Here is how we can compute a confidence interval for the difference between this sub-group, and Enrofloxacin.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-5-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-1" role="tab" aria-controls="tabset-5-1" aria-selected="true">R code</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-2" role="tab" aria-controls="tabset-5-2" aria-selected="false">Python code</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-3" role="tab" aria-controls="tabset-5-3" aria-selected="false">SAS code</a></li></ul>
<div class="tab-content">
<div id="tabset-5-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-5-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1"></a>c1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="fl">0.5</span>, <span class="fl">0.5</span>)</span>
<span id="cb17-2"><a href="#cb17-2"></a>n_vals <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">6</span>, <span class="dv">6</span>, <span class="dv">6</span>)</span>
<span id="cb17-3"><a href="#cb17-3"></a>L <span class="ot">&lt;-</span> <span class="fu">sum</span>(c1<span class="sc">*</span>est_coef[<span class="dv">3</span><span class="sc">:</span><span class="dv">5</span>])</span>
<span id="cb17-4"><a href="#cb17-4"></a></span>
<span id="cb17-5"><a href="#cb17-5"></a><span class="co">#MSW &lt;- summary_out[[1]]$`Mean Sq`[2]</span></span>
<span id="cb17-6"><a href="#cb17-6"></a><span class="co">#df &lt;- summary_out[[1]]$Df[2]</span></span>
<span id="cb17-7"><a href="#cb17-7"></a>se1 <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(MSW <span class="sc">*</span> <span class="fu">sum</span>( c1<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> n_vals ) )</span>
<span id="cb17-8"><a href="#cb17-8"></a></span>
<span id="cb17-9"><a href="#cb17-9"></a>q1 <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="fl">0.025</span>, df, <span class="dv">0</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb17-10"><a href="#cb17-10"></a></span>
<span id="cb17-11"><a href="#cb17-11"></a>lower_ci <span class="ot">&lt;-</span> L <span class="sc">-</span> q1<span class="sc">*</span>se1</span>
<span id="cb17-12"><a href="#cb17-12"></a>upper_ci <span class="ot">&lt;-</span> L <span class="sc">+</span> q1<span class="sc">*</span>se1</span>
<span id="cb17-13"><a href="#cb17-13"></a><span class="fu">cat</span>(<span class="st">"The 95% CI for the diff. between the two groups is ("</span>,</span>
<span id="cb17-14"><a href="#cb17-14"></a>    <span class="fu">format</span>(lower_ci, <span class="at">digits =</span> <span class="dv">2</span>), <span class="st">","</span>, </span>
<span id="cb17-15"><a href="#cb17-15"></a>    <span class="fu">format</span>(upper_ci, <span class="at">digits =</span> <span class="dv">2</span>), <span class="st">")."</span>, <span class="at">sep=</span><span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The 95% CI for the diff. between the two groups is (0.083,0.33).</code></pre>
</div>
</div>
</div>
<div id="tabset-5-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1"></a>c1 <span class="op">=</span> np.array([<span class="op">-</span><span class="dv">1</span>, <span class="fl">0.5</span>, <span class="fl">0.5</span>])</span>
<span id="cb19-2"><a href="#cb19-2"></a>n_vals <span class="op">=</span> np.array([<span class="dv">6</span>, <span class="dv">6</span>, <span class="dv">6</span>,])</span>
<span id="cb19-3"><a href="#cb19-3"></a>L <span class="op">=</span> np.<span class="bu">sum</span>(c1 <span class="op">*</span> heifer_lm.params.iloc[<span class="dv">2</span>:<span class="dv">5</span>])</span>
<span id="cb19-4"><a href="#cb19-4"></a></span>
<span id="cb19-5"><a href="#cb19-5"></a>MSW <span class="op">=</span> heifer_lm.mse_resid</span>
<span id="cb19-6"><a href="#cb19-6"></a>df <span class="op">=</span> heifer_lm.df_resid</span>
<span id="cb19-7"><a href="#cb19-7"></a>q1 <span class="op">=</span> <span class="op">-</span>stats.t.ppf(<span class="fl">0.025</span>, df)</span>
<span id="cb19-8"><a href="#cb19-8"></a>se1 <span class="op">=</span> np.sqrt(MSW<span class="op">*</span>np.<span class="bu">sum</span>(c1<span class="op">**</span><span class="dv">2</span> <span class="op">/</span> n_vals))</span>
<span id="cb19-9"><a href="#cb19-9"></a></span>
<span id="cb19-10"><a href="#cb19-10"></a>lower_ci <span class="op">=</span> L <span class="op">-</span> q1<span class="op">*</span>se1</span>
<span id="cb19-11"><a href="#cb19-11"></a>upper_ci <span class="op">=</span> L <span class="op">+</span> q1<span class="op">*</span>se1</span>
<span id="cb19-12"><a href="#cb19-12"></a><span class="bu">print</span>(<span class="ss">f"""The 95% CI for the diff. between the two groups is </span></span>
<span id="cb19-13"><a href="#cb19-13"></a><span class="ss">(</span><span class="sc">{</span>lower_ci<span class="sc">:.3f}</span><span class="ss">, </span><span class="sc">{</span>upper_ci<span class="sc">:.3f}</span><span class="ss">)."""</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The 95% CI for the diff. between the two groups is 
(0.083, 0.332).</code></pre>
</div>
</div>
</div>
<div id="tabset-5-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-3-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1"></a>proc glm data<span class="ot">=</span>ST2137.HEIFERS;</span>
<span id="cb21-2"><a href="#cb21-2"></a>    class type;</span>
<span id="cb21-3"><a href="#cb21-3"></a>    model org<span class="ot">=</span>type <span class="sc">/</span> clparm;</span>
<span id="cb21-4"><a href="#cb21-4"></a>    means type <span class="sc">/</span> hovtest<span class="ot">=</span>levene welch plots<span class="ot">=</span>none;</span>
<span id="cb21-5"><a href="#cb21-5"></a>    lsmeans type <span class="sc">/</span> adjust<span class="ot">=</span>tukey pdiff alpha<span class="ot">=</span>.<span class="dv">05</span>;</span>
<span id="cb21-6"><a href="#cb21-6"></a>    estimate <span class="st">'group_A_vs_enro'</span> type <span class="dv">0</span> <span class="dv">0</span> <span class="sc">-</span><span class="dv">1</span> <span class="fl">0.5</span> <span class="fl">0.5</span> <span class="dv">0</span>;</span>
<span id="cb21-7"><a href="#cb21-7"></a>    output out<span class="ot">=</span>work.Oneway_stats r<span class="ot">=</span>residual;</span>
<span id="cb21-8"><a href="#cb21-8"></a>    run;</span>
<span id="cb21-9"><a href="#cb21-9"></a>quit;</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/sas_anova_heifer_contrast2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="multiple-comparisons" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="multiple-comparisons"><span class="header-section-number">8.5</span> Multiple Comparisons</h2>
<p>The procedures in the previous two subsections correspond to contrasts that we had specified before collecting or studying the data. If, instead, we wished to perform particular comparisons after studying the group means, or if we wish to compute all pairwise contrasts, then we need to adjust for the fact that we are conducting multiple tests. If we do not do so, the chance of making at least one false positive increases greatly.</p>
<section id="bonferroni" class="level3">
<h3 class="anchored" data-anchor-id="bonferroni">Bonferroni</h3>
<p>The simplest method for correcting for multiple comparisons is to use the Bonferroni correction. Suppose we wish to perform <span class="math inline">\(m\)</span> pairwise comparisons, either as a test or by computing confidence intervals. If we wish to maintain the significance level of each test at <span class="math inline">\(\alpha\)</span>, then we should perform each of the <span class="math inline">\(m\)</span> tests/confidence intervals at <span class="math inline">\(\alpha/m\)</span>.</p>
</section>
<section id="tukeyhsd" class="level3">
<h3 class="anchored" data-anchor-id="tukeyhsd">TukeyHSD</h3>
<p>This procedure is known as Tukey’s Honestly Significant Difference. It is designed to construct confidence intervals for <strong>all</strong> pairwise comparisons. For the same <span class="math inline">\(\alpha\)</span>-level, Tukey’s HSD method provides shorter confidence intervals than a Bonferroni correction for all pairwise comparisons.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-6-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-1" role="tab" aria-controls="tabset-6-1" aria-selected="true">R code</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-6-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-2" role="tab" aria-controls="tabset-6-2" aria-selected="false">Python code</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-6-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-3" role="tab" aria-controls="tabset-6-3" aria-selected="false">SAS output</a></li></ul>
<div class="tab-content">
<div id="tabset-6-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-6-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a><span class="fu">TukeyHSD</span>(<span class="fu">aov</span>(heifers_lm), <span class="at">ordered =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level
    factor levels have been ordered

Fit: aov(formula = heifers_lm)

$type
                        diff         lwr       upr     p adj
Enroflox-Control  0.10666667 -0.10812638 0.3214597 0.6563131
Fenbenda-Control  0.23000000  0.01520695 0.4447930 0.0304908
Spiramyc-Control  0.25166667  0.01152074 0.4918126 0.0358454
Alfacyp-Control   0.29166667  0.07687362 0.5064597 0.0034604
Ivermect-Control  0.39833333  0.18354028 0.6131264 0.0000612
Fenbenda-Enroflox 0.12333333 -0.09145972 0.3381264 0.5093714
Spiramyc-Enroflox 0.14500000 -0.09514593 0.3851459 0.4549043
Alfacyp-Enroflox  0.18500000 -0.02979305 0.3997930 0.1225956
Ivermect-Enroflox 0.29166667  0.07687362 0.5064597 0.0034604
Spiramyc-Fenbenda 0.02166667 -0.21847926 0.2618126 0.9997587
Alfacyp-Fenbenda  0.06166667 -0.15312638 0.2764597 0.9488454
Ivermect-Fenbenda 0.16833333 -0.04645972 0.3831264 0.1923280
Alfacyp-Spiramyc  0.04000000 -0.20014593 0.2801459 0.9953987
Ivermect-Spiramyc 0.14666667 -0.09347926 0.3868126 0.4424433
Ivermect-Alfacyp  0.10666667 -0.10812638 0.3214597 0.6563131</code></pre>
</div>
</div>
</div>
<div id="tabset-6-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-6-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1"></a><span class="im">import</span> statsmodels.stats.multicomp <span class="im">as</span> mc</span>
<span id="cb24-2"><a href="#cb24-2"></a></span>
<span id="cb24-3"><a href="#cb24-3"></a>cp <span class="op">=</span> mc.MultiComparison(heifers.org, heifers.<span class="bu">type</span>)</span>
<span id="cb24-4"><a href="#cb24-4"></a>tk <span class="op">=</span> cp.tukeyhsd()</span>
<span id="cb24-5"><a href="#cb24-5"></a><span class="bu">print</span>(tk)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Multiple Comparison of Means - Tukey HSD, FWER=0.05   
========================================================
 group1   group2  meandiff p-adj   lower   upper  reject
--------------------------------------------------------
 Alfacyp  Control  -0.2917 0.0035 -0.5065 -0.0769   True
 Alfacyp Enroflox   -0.185 0.1226 -0.3998  0.0298  False
 Alfacyp Fenbenda  -0.0617 0.9488 -0.2765  0.1531  False
 Alfacyp Ivermect   0.1067 0.6563 -0.1081  0.3215  False
 Alfacyp Spiramyc    -0.04 0.9954 -0.2801  0.2001  False
 Control Enroflox   0.1067 0.6563 -0.1081  0.3215  False
 Control Fenbenda     0.23 0.0305  0.0152  0.4448   True
 Control Ivermect   0.3983 0.0001  0.1835  0.6131   True
 Control Spiramyc   0.2517 0.0358  0.0115  0.4918   True
Enroflox Fenbenda   0.1233 0.5094 -0.0915  0.3381  False
Enroflox Ivermect   0.2917 0.0035  0.0769  0.5065   True
Enroflox Spiramyc    0.145 0.4549 -0.0951  0.3851  False
Fenbenda Ivermect   0.1683 0.1923 -0.0465  0.3831  False
Fenbenda Spiramyc   0.0217 0.9998 -0.2185  0.2618  False
Ivermect Spiramyc  -0.1467 0.4424 -0.3868  0.0935  False
--------------------------------------------------------</code></pre>
</div>
</div>
</div>
<div id="tabset-6-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-6-3-tab">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/sas_anova_heifer_hsd.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="kruskal-wallis-procedure" class="level2" data-number="8.6">
<h2 data-number="8.6" class="anchored" data-anchor-id="kruskal-wallis-procedure"><span class="header-section-number">8.6</span> Kruskal-Wallis Procedure</h2>
<p>If the assumptions of the ANOVA procedure are not met, we can turn to a non-parametric version - the Kruskal Wallis test. This latter procedure is a generalisation of the Wilcoxon Rank-Sum test for 2 independent samples.</p>
<section id="formal-set-up-1" class="level3">
<h3 class="anchored" data-anchor-id="formal-set-up-1">Formal Set-up</h3>
<p>The test statistic compares the average ranks in the individual groups. If these are close together, we would be inclined to conclude the treatments are equally effective.</p>
<p>The null hypothesis is that all groups follow the same distribution. The alternative hypothesis is that at least one of the groups’ distribution differs from another by a location shift. We then proceed with:</p>
<ol type="1">
<li><p>Pool the observations over all samples, thus constructing a combined sample of size <span class="math inline">\(N = \sum n_i\)</span>. Assign ranks to individual observations, using average rank in the case of tied observations. Compute the rank sum <span class="math inline">\(R_i\)</span> for each of the <span class="math inline">\(k\)</span> samples.</p></li>
<li><p>If there are no ties, compute the test statistic as <span class="math display">\[
H = \frac{12}{N(N+1)} \sum_{i=1}^k \frac{R_i^2}{n_i} - 3(N+1)
\]</span></p></li>
<li><p>If there <em>are</em> ties, compute the test statistic as <span class="math display">\[
H^* = \frac{H}{1 - \frac{\sum_{j=1}^g (t^3_j - t_j)}{N^3 - N}}
\]</span></p>
<p>where <span class="math inline">\(t_j\)</span> refers to the number of observations with the same value in the <span class="math inline">\(j\)</span>-th cluster of tied observations and <span class="math inline">\(g\)</span> is the number of tied groups.</p></li>
</ol>
<p>Under <span class="math inline">\(H_0\)</span>, the test statistic follows a <span class="math inline">\(\chi^2\)</span> distribution with <span class="math inline">\(k-1\)</span> degrees of freedom.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>This test should only be used if <span class="math inline">\(n_i \ge 5\)</span> for all groups.</p>
</div>
</div>
<div id="exm-antibiotics-4" class="theorem example" style="background-color: #D5D1D1; padding: 20px">
<p><span class="theorem-title"><strong>Example 8.5 (Kruskal-Wallis Test)</strong></span> </p>
<p>Here is the code and output from running the Kruskal-Wallis test in the three software.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-7-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-1" role="tab" aria-controls="tabset-7-1" aria-selected="true">R code</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-7-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-2" role="tab" aria-controls="tabset-7-2" aria-selected="false">Python code</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-7-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-3" role="tab" aria-controls="tabset-7-3" aria-selected="false">SAS output</a></li></ul>
<div class="tab-content">
<div id="tabset-7-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-7-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a><span class="fu">kruskal.test</span>(heifers<span class="sc">$</span>org, heifers<span class="sc">$</span>type)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  heifers$org and heifers$type
Kruskal-Wallis chi-squared = 19.645, df = 5, p-value = 0.001457</code></pre>
</div>
</div>
</div>
<div id="tabset-7-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-7-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1"></a>out <span class="op">=</span> [x[<span class="dv">1</span>] <span class="cf">for</span> x <span class="kw">in</span> heifers.org.groupby(heifers.<span class="bu">type</span>)]</span>
<span id="cb28-2"><a href="#cb28-2"></a>kw_out <span class="op">=</span> stats.kruskal(<span class="op">*</span>out)</span>
<span id="cb28-3"><a href="#cb28-3"></a><span class="bu">print</span>(<span class="ss">f"""The test statistic is </span><span class="sc">{</span>kw_out<span class="sc">.</span>statistic<span class="sc">:.3f}</span><span class="ss">,</span></span>
<span id="cb28-4"><a href="#cb28-4"></a><span class="ss">the p-value is </span><span class="sc">{</span>kw_out<span class="sc">.</span>pvalue<span class="sc">:.3f}</span><span class="ss">."""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The test statistic is 19.645,
the p-value is 0.001.</code></pre>
</div>
</div>
</div>
<div id="tabset-7-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-7-3-tab">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/sas_kruskal_wallis_a.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="summary" class="level2" data-number="8.7">
<h2 data-number="8.7" class="anchored" data-anchor-id="summary"><span class="header-section-number">8.7</span> Summary</h2>
<p>The purpose of this topic is to introduce you to the one-way ANOVA model. While there are restrictive distributional assumptions that it entails, I once again urge you to look past, at the information the method conveys. It attempts to compare the within-group variance to the between-group variance. Try to avoid viewing statistical procedures as flowcharts. If an assumption does not hold, or a p-value is borderline significant, try to investigate further on how sensitive the result is to those assumptions.</p>
<p>Our job as analysts does not end after reporting the p-value from the <span class="math inline">\(F\)</span>-test. We should try to dig deeper to uncover which groups are the ones that are different from the rest.</p>
<p>Finally, take note that we should specify the contrasts we wish to test/estimate upfront, even before collecting the data. Only the Tukey comparison method (HSD) is valid if we perform multiple comparisons after inspecting the data.</p>
<p>Most of the theoretical portions in this topic were taken from the textbook <span class="citation" data-cites="rosner2015fundamentals">Rosner (<a href="references.html#ref-rosner2015fundamentals" role="doc-biblioref">2015</a>)</span>.</p>
</section>
<section id="references" class="level2" data-number="8.8">
<h2 data-number="8.8" class="anchored" data-anchor-id="references"><span class="header-section-number">8.8</span> References</h2>
<section id="sec-web-ref-08" class="level3">
<h3 class="anchored" data-anchor-id="sec-web-ref-08">Website References</h3>
<ol type="1">
<li><a href="https://statisticsbyjim.com/anova/welchs-anova-compared-to-classic-one-way-anova/">Welch’s ANOVA</a> This website discusses an alternative test when the equal variance assumption has not been satisfied. It is for information only; it will not be tested.</li>
<li><a href="https://docs.scipy.org/doc/scipy/reference/stats.html">scipy stats</a> This website contains documentation on the distribution-related functions that we might need from scipy stats, e.g.&nbsp;retrieving quantiles.</li>
<li><a href="https://stats.oarc.ucla.edu/r/library/r-library-contrast-coding-systems-for-categorical-variables/">Contrast coding</a></li>
<li><a href="https://rcompanion.org/rcompanion/d_04.html">Type I,II,III SS</a></li>
</ol>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-ekstrom2015statistical" class="csl-entry" role="listitem">
Ekstrøm, Claus Thorn, and Helle Sørensen. 2015. <span>“Statistical Data Analysis for the Life Sciences.”</span> CRC Press, London.
</div>
<div id="ref-rosner2015fundamentals" class="csl-entry" role="listitem">
Rosner, Bernard. 2015. <em>Fundamentals of Biostatistics</em>. Cengage learning.
</div>
</div>
</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>A heifer is a young, female cow that has not had her first calf yet.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./07-2_sample_tests.html" class="pagination-link  aria-label=" &lt;span="" hypothesis="" tests&lt;="" span&gt;"="">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Two-sample Hypothesis Tests</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./09-regression.html" class="pagination-link" aria-label="<span class='chapter-number'>9</span>&nbsp; <span class='chapter-title'>Linear Regression</span>">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Linear Regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>